### ISSUE TITLE
No install instructions?

### ISSUE THREAD

**Issue by Sophrinix** [damiles/blendocv#1]
Can you please provide a readme that at a minimum explains how to compile this?

**Comment by damiles** [comment]
Hi, it's very early to explain how to compile due there are a lot of tasks to do before i release the first beta version and show how compile and contribute in this project. 

Please be patient.

**Comment by Sophrinix** [comment]
Part of the problem is they I'm on OSX 10.9. Your gnumakefile doesn't know about that version. 

I've compiled  opencv lots of times and I've compiled blender before, but your doing something different with the make file

**Comment by damiles** [comment]
i'm on OSX 10.9 to, and i compile with CMake, configure the paths and disable the tools that are not required for BlendOcv and compile with make.

Now i'm working in develop some more nodes, and later, clean the UI from tools and libraries that are not required for BlendOcv. Then i'm available to publish documentation about how to compile and release the compiled versions.

**Comment by jamesguo** [comment]
I compile with 'cmake -G "Unix Makefiles"'  on OSX 10.8.5
Error at CmakeLists.txt:line 35

**Comment by damiles** [comment]
1. BlendOcv is now pre-Beta and there are a lot of work todo before people can compile and test.
2. There are only few nodes implemented and i have to create more nodes.
3. There are hundred of Blender dependencies that BlendOcv don't need and i will have to  clean CmakeLists.txt files.

You compiler error is because you are trying compile in the same folder as source.
