### ISSUE TITLE
How To compile& install on OSX 10.8.5

### ISSUE THREAD

**Issue by jamesguo** [damiles/blendocv#2]
I compile with 'cmake -G "Unix Makefiles"' on OSX 10.8.5
Error at CmakeLists.txt:line 35

**Comment by damiles** [comment]
1. BlendOcv is now pre-Beta and there are a lot of work todo before people can compile and test.
2. There are only few nodes implemented and i have to create more nodes.
3. There are hundred of Blender dependencies that BlendOcv don't need and i will have to  clean CmakeLists.txt files.

You compiler error is because you are trying compile in the same folder as source.
